// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-zfwPI2DyZseQOl5ZBAA9Uh_GA1EMfLQ',
    appId: '1:127085407708:web:02a0da148b93b090a47319',
    messagingSenderId: '127085407708',
    projectId: 'odcproject-e4f72',
    authDomain: 'odcproject-e4f72.firebaseapp.com',
    storageBucket: 'odcproject-e4f72.appspot.com',
    measurementId: 'G-ND7R26KC5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEnkx_EdYBldBLob_y1_Qe0FkaDbWUG08',
    appId: '1:127085407708:android:b7436b5d2f20b820a47319',
    messagingSenderId: '127085407708',
    projectId: 'odcproject-e4f72',
    storageBucket: 'odcproject-e4f72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBnedUDC9phj5aS5_jnXBkUSxQZzUmNwQ',
    appId: '1:127085407708:ios:8373b718da6b821aa47319',
    messagingSenderId: '127085407708',
    projectId: 'odcproject-e4f72',
    storageBucket: 'odcproject-e4f72.appspot.com',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBnedUDC9phj5aS5_jnXBkUSxQZzUmNwQ',
    appId: '1:127085407708:ios:8373b718da6b821aa47319',
    messagingSenderId: '127085407708',
    projectId: 'odcproject-e4f72',
    storageBucket: 'odcproject-e4f72.appspot.com',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-zfwPI2DyZseQOl5ZBAA9Uh_GA1EMfLQ',
    appId: '1:127085407708:web:9bd2d2666be34814a47319',
    messagingSenderId: '127085407708',
    projectId: 'odcproject-e4f72',
    authDomain: 'odcproject-e4f72.firebaseapp.com',
    storageBucket: 'odcproject-e4f72.appspot.com',
    measurementId: 'G-G49YLF1F5Y',
  );
}
